name: inkling_personal
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.2
  file_picker: ^3.0.2+2
  firebase_core: ^1.2.0
  firebase_storage: ^8.1.0
  flutter_bloc: ^7.0.0
  flutter_dotenv: ^5.0.0
  flutter_secure_storage: ^4.2.0
  http: ^0.13.3
  razorpay_flutter: ^1.2.6
  syncfusion_flutter_pdfviewer: ^19.1.65-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env
